### ISSUE TITLE
Plain text output option / ASCI bar character.

### ISSUE THREAD

**Issue by davidjeddy** [jez/git-heatmap#2]
First off, awesome tool! Not only is it fast but within an hour I was able to generate a report that assisted in convincing the business side of an organization to invest in refactoring and reducing technical debt. Well done, and thank you.

Now onto the request part: Any option to output the results in plain ASCI characters. Specifically no colored text and instead of bar characters use '-' or '=' etc. The idea behind this is to ouput the text, sed it into a basic HTML wrapper and have it available as a report as part of the result of a automated testing cycle. Currently the CLI coloring and the bar characters do not translate well from strout to a text file.

Thank you again for this tool, as is it is super helpful!

**Comment by jez** [comment]
Yeah this is a simple change. Give me a minute or two to finish lunch and I
can do it.

Glad this was useful for you!

**Comment by jez** [comment]
Done in 0.10.0

See: https://github.com/jez/git-heatmap#usage

You should be able to run this:

```
git heatmap --char = > output.txt
```

Use whatever `char` you want.

It will automatically detect if you are outputing to a terminal / tty and only enable color if you are. Piped output / output to a file will not have colors.

**Comment by davidjeddy** [comment]
Derp, it would appear brew installs 0.9.0; to get 0.10.3 requires executing `brew upgrade git-heatmap`. Once updated everything worked as expected.

Suggestion: update brew installed version.
