### ISSUE TITLE
Option to exclude files

### ISSUE THREAD

**Issue by kairichard** [jez/git-heatmap#3]
Looks really neat but with large repos and automated process that do commits it can become handy to exclude some files from being listed.

**Comment by jez** [comment]
This is now available in 0.10.3. For example, to exclude files matching the pattern `*.test.js`:

```
git heatmap --filter 'grep -v ".*\.test\.js"'
```

You can pass an arbitrary command to `--filter`.

Usage: https://github.com/jez/git-heatmap#usage

**Comment by kairichard** [comment]
Great thank you very much!
