### ISSUE TITLE
Please explain “oft-edited files”

### ISSUE THREAD

**Issue by alexisLefebvre** [jez/git-heatmap#4]
English is not my mother tongue and I don't understand what is **oft** in “oft-edited files”, can you please explain it somewhere or use a simpler term?

It is written in project's description and in the README.

**Comment by jez** [comment]
"oft-" is just an abbreviation of "often" that can be used as a word prefix:

- oft-edited → edited often
- oft-quoted → quoted often
- ...

**Comment by alexisLefebvre** [comment]
Thanks for your answer, I didn't know that.
